/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NavRouteImport } from './routes/nav'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSpaceRouteImport } from './routes/projects.space'
import { Route as ProjectsIllustrationRouteImport } from './routes/projects.illustration'
import { Route as ProjectsGraphicRouteImport } from './routes/projects.graphic'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NavRoute = NavRouteImport.update({
  id: '/nav',
  path: '/nav',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSpaceRoute = ProjectsSpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIllustrationRoute = ProjectsIllustrationRouteImport.update({
  id: '/illustration',
  path: '/illustration',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsGraphicRoute = ProjectsGraphicRouteImport.update({
  id: '/graphic',
  path: '/graphic',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/nav': typeof NavRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/graphic': typeof ProjectsGraphicRoute
  '/projects/illustration': typeof ProjectsIllustrationRoute
  '/projects/space': typeof ProjectsSpaceRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/nav': typeof NavRoute
  '/projects/graphic': typeof ProjectsGraphicRoute
  '/projects/illustration': typeof ProjectsIllustrationRoute
  '/projects/space': typeof ProjectsSpaceRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/nav': typeof NavRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/graphic': typeof ProjectsGraphicRoute
  '/projects/illustration': typeof ProjectsIllustrationRoute
  '/projects/space': typeof ProjectsSpaceRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/nav'
    | '/projects'
    | '/projects/graphic'
    | '/projects/illustration'
    | '/projects/space'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/nav'
    | '/projects/graphic'
    | '/projects/illustration'
    | '/projects/space'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/nav'
    | '/projects'
    | '/projects/graphic'
    | '/projects/illustration'
    | '/projects/space'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  ContactRoute: typeof ContactRoute
  NavRoute: typeof NavRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nav': {
      id: '/nav'
      path: '/nav'
      fullPath: '/nav'
      preLoaderRoute: typeof NavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/space': {
      id: '/projects/space'
      path: '/space'
      fullPath: '/projects/space'
      preLoaderRoute: typeof ProjectsSpaceRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/illustration': {
      id: '/projects/illustration'
      path: '/illustration'
      fullPath: '/projects/illustration'
      preLoaderRoute: typeof ProjectsIllustrationRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/graphic': {
      id: '/projects/graphic'
      path: '/graphic'
      fullPath: '/projects/graphic'
      preLoaderRoute: typeof ProjectsGraphicRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsGraphicRoute: typeof ProjectsGraphicRoute
  ProjectsIllustrationRoute: typeof ProjectsIllustrationRoute
  ProjectsSpaceRoute: typeof ProjectsSpaceRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsGraphicRoute: ProjectsGraphicRoute,
  ProjectsIllustrationRoute: ProjectsIllustrationRoute,
  ProjectsSpaceRoute: ProjectsSpaceRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  ContactRoute: ContactRoute,
  NavRoute: NavRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
